[platformio]
; Use your existing sketch folder as the "src" directory
src_dir = firmware/CatShelterLogger_v1_1

[env:feather_nrf52840]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
monitor_speed = 115200

lib_deps =
  adafruit/Adafruit FRAM SPI@^2
  adafruit/RTClib@^2
  paulstoffregen/OneWire@^2
  milesburton/DallasTemperature@^3
